[package]
name = "note-lsm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.131"
comfy-table = "7.1.1"
eyre = "0.6"
tokio = "1"

note-lsm-lib = { path = "../../lib" }
